apiVersion: v1
kind: ConfigMap
metadata:
  name: devpocket-config
  namespace: devpocket-prod
data:
  APP_NAME: "DevPocket API"
  ENVIRONMENT: "production"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  DATABASE_NAME: "devpocket"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  CONTAINER_REGISTRY: "docker.io"
  CONTAINER_CPU_LIMIT: "1000m"
  CONTAINER_MEMORY_LIMIT: "2Gi"
  CONTAINER_STORAGE_LIMIT: "10Gi"
