apiVersion: v1
kind: Service
metadata:
  name: devpocket-server-service
  namespace: devpocket-prod
  labels:
    app: devpocket-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: devpocket-server
